# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-18 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumplateResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_result', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payload', models.CharField(blank=True, default='', max_length=10)),
                ('result', models.CharField(blank=True, max_length=100, null=True)),
                ('image_id', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
