# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-12 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_rnpdtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rnpduploadfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payload', models.CharField(blank=True, default='', max_length=10)),
                ('filename', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
