# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-20 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_numplateresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnpdtoken',
            name='token_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
