# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-12 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_rnpduploadfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rnpduploadfile',
            options={'ordering': ('created',)},
        ),
        migrations.RemoveField(
            model_name='rnpduploadfile',
            name='payload',
        ),
    ]
