# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-24 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_auto_20180820_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnpdtoken',
            name='token_key',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
