# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-13 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_auto_20180812_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnpduploadfile',
            name='token_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
