# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-13 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_rnpduploadfile_token_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rnpduploadfile',
            name='token_key',
        ),
    ]
