# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-29 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_auto_20180828_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rnpdtoken',
            old_name='token_key1',
            new_name='token_key',
        ),
    ]
