# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-09 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_auto_20180829_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnpdtoken',
            name='token_key',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
