# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-11 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_auto_20180911_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rnpdtoken',
            name='useremail',
        ),
    ]
